@extends('pdfs.layout')

@section('title', 'Measurement Card — v' . $version->version_number)

@section('doc-meta')
    <strong>Measurement Card</strong><br>
    <span class="doc-number">v{{ $version->version_number }}</span><br>
    @if($version->status === 'approved')
        <span class="status-badge status-approved">Approved</span>
    @else
        <span class="status-badge status-pending">{{ ucfirst($version->status) }}</span>
    @endif
@endsection

@section('content')
    <div class="info-grid">
        <div class="info-grid__col">
            <div class="section-label">Customer</div>
            <div class="info-row">
                <div class="info-row__value">{{ $version->profile?->customer?->name ?? '—' }}</div>
                @if($version->profile?->customer?->phone)
                    <div class="info-row__label">{{ $version->profile->customer->phone }}</div>
                @endif
            </div>
        </div>
        <div class="info-grid__col">
            <div class="section-label">Version Info</div>
            <div class="info-row">
                <div class="info-row__label">Version</div>
                <div class="info-row__value">v{{ $version->version_number }}</div>
            </div>
            @if($version->approved_at)
            <div class="info-row">
                <div class="info-row__label">Approved</div>
                <div class="info-row__value">{{ optional($version->approved_at)->format('d M Y') }}</div>
            </div>
            @endif
        </div>
    </div>

    @if(!empty($version->shirt_data))
    <div class="section-label">Shirt Measurements</div>
    <div class="measurement-grid">
        @php $chunks = array_chunk(array_keys($version->shirt_data), 4, true) @endphp
        @foreach($chunks as $row)
        <div class="measurement-row">
            @foreach($row as $field)
            <div class="measurement-cell">
                <div class="measurement-cell__label">{{ ucwords(str_replace('_', ' ', $field)) }}</div>
                <div class="measurement-cell__value">{{ is_scalar($version->shirt_data[$field]) ? $version->shirt_data[$field] : '—' }} <span class="measurement-cell__unit">cm</span></div>
            </div>
            @endforeach
            @for($i = count($row); $i < 4; $i++)
            <div class="measurement-cell" style="background:transparent;"></div>
            @endfor
        </div>
        @endforeach
    </div>
    @endif

    @if(!empty($version->pant_data))
    <div class="section-label">Pant Measurements</div>
    <div class="measurement-grid">
        @php $chunks = array_chunk(array_keys($version->pant_data), 4, true) @endphp
        @foreach($chunks as $row)
        <div class="measurement-row">
            @foreach($row as $field)
            <div class="measurement-cell">
                <div class="measurement-cell__label">{{ ucwords(str_replace('_', ' ', $field)) }}</div>
                <div class="measurement-cell__value">{{ is_scalar($version->pant_data[$field]) ? $version->pant_data[$field] : '—' }} <span class="measurement-cell__unit">cm</span></div>
            </div>
            @endforeach
            @for($i = count($row); $i < 4; $i++)
            <div class="measurement-cell" style="background:transparent;"></div>
            @endfor
        </div>
        @endforeach
    </div>
    @endif

    @if($version->notes)
    <div class="section-label">Notes</div>
    <div style="padding: 8px 10px; background: #FFFBEB; border: 1px solid #FDE68A; border-radius: 4px; font-size: 10.5px; color: #374151;">
        {{ $version->notes }}
    </div>
    @endif

    <div style="display:table; width:100%; margin-top: 24px;">
        <div style="display:table-cell; width:50%;">
            <div class="signature-line">Measurement Staff</div>
        </div>
        <div style="display:table-cell; width:50%; padding-left:20px;">
            <div class="signature-line">Approver Signature</div>
        </div>
    </div>
@endsection

@section('footer-left', 'Measurement Card · v' . $version->version_number . ' · Append-only versioned')
@section('footer-right', 'Generated by Solo Shirts ERP')
